frontend:
  image:
    repository: asia-south1-docker.pkg.dev/mathverse-platform-dev/mathverse-repo/mathverse-frontend
    tag: stable

backend:
  image:
    repository: asia-south1-docker.pkg.dev/mathverse-platform-dev/mathverse-repo/mathverse-backend
    tag: stable

replicaCount: 3